export const Floor1 = [
    { id: 1, name: 'T01', status: 'Vacant clean' },
    { id: 2, name: 'T02', status: 'In Service' },
    { id: 3, name: 'T03', status: 'Vacant clean' },
    { id: 4, name: 'T04', status: 'In Service' },
    { id: 5, name: 'T05', status: 'Reserved' },
    { id: 6, name: 'T06', status: 'In Service' },
    { id: 7, name: 'T07', status: 'Vacant clean' },
    { id: 8, name: 'T08', status: 'Reserved' },
    { id: 9, name: 'T09', status: 'In Service' },
    { id: 10, name: 'T10', status: 'Vacant dirty' },
    { id: 11, name: 'T11', status: 'In Service' },
    { id: 12, name: 'T12', status: 'Vacant dirty' },
];
export const Floor2 = [
    { id: 1, name: 'T01', status: 'Vacant clean' },
    { id: 2, name: 'T02', status: 'In Service' },
    { id: 3, name: 'T03', status: 'Vacant clean' },
    { id: 4, name: 'T04', status: 'In Service' },
    { id: 5, name: 'T05', status: 'Reserved' },
    { id: 6, name: 'T06', status: 'In Service' },
    { id: 7, name: 'T07', status: 'Vacant clean' },
    { id: 8, name: 'T08', status: 'Reserved' },
    { id: 9, name: 'T09', status: 'In Service' },
    { id: 10, name: 'T10', status: 'Vacant dirty' },
    { id: 11, name: 'T11', status: 'In Service' },
    { id: 12, name: 'T12', status: 'Vacant dirty' },
];
export const Floor3 = [
    { id: 1, name: 'T01', status: 'Vacant clean' },
    { id: 2, name: 'T02', status: 'In Service' },
    { id: 3, name: 'T03', status: 'Vacant clean' },
    { id: 4, name: 'T04', status: 'In Service' },
    { id: 5, name: 'T05', status: 'Reserved' },
    { id: 6, name: 'T06', status: 'In Service' },
    { id: 7, name: 'T07', status: 'Vacant clean' },
    { id: 8, name: 'T08', status: 'Reserved' },
    { id: 9, name: 'T09', status: 'In Service' },
    { id: 10, name: 'T10', status: 'Vacant dirty' },
    { id: 11, name: 'T11', status: 'In Service' },
    { id: 12, name: 'T12', status: 'Vacant dirty' },
];
